name: estimatingmicrodsops
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - jupyterlab
  - black 
  - ruff 
  - nbqa
  - dask 
  - estimagic
  - openpyxl
  - pip
  - pip:
      - git+https://github.com/econ-ark/HARK@SimplifySolvers
      - black[jupyter]
      - -e ./code/
